pub mod admin;
pub mod auth;
pub mod availability;
pub mod booking;
pub mod business;
pub mod catalog;
pub mod clients;
pub mod error;
pub mod extract;
pub mod health;
pub mod profile;
pub mod public;
pub mod routes;
pub mod schedule;
pub mod state;
pub mod team;

pub use routes::create_router;
pub use state::AppState;
