-- Migration: Cleanup test data from global catalog
-- Leaves only real products (standard ones and those with images)

-- 1. Remove "Expiring Fish" and products with hex suffixes (autogenerated by test scripts)
DELETE FROM catalog_ingredients 
WHERE name_en LIKE 'Expiring Fish%'
   OR name_en ~ '[a-f0-9]{8}$';

-- 2. Remove any other products that might have been created by stress-test scripts
DELETE FROM catalog_ingredients
WHERE name_en LIKE 'Test %'
   OR name_en LIKE 'Dummy %';
