-- ══════════════════════════════════════════════════════════════════════════════
-- SUSHI-GRADE AUTO-SEASONALITY — Single Source of Truth Architecture
--
-- DB triggers are the ONLY place that manages seasonality lifecycle.
-- Rust code does NOT call generate_seasonality — zero dual-write.
--
-- Changes:
--   1. Trigger: sushi_grade → true  → generate seasonality with peak support
--   2. Trigger: sushi_grade → false → cleanup auto-generated rows (source tracking)
--   3. Add updated_at column for sitemap / Google freshness signals
--   4. Add composite lookup index for best-in-season / fish-calendar queries
--   5. Add source column to track who created the row (manual / auto / sushi_auto)
--   6. Backfill: eel = sushi_grade true
-- ══════════════════════════════════════════════════════════════════════════════

-- ── 1. Schema improvements ───────────────────────────────────────────────────

-- updated_at: sitemap can use this, Google sees freshness
ALTER TABLE catalog_product_seasonality
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- source: track who created the row (for safe cleanup on sushi_grade → false)
-- 'manual'     — admin set it via migration or direct SQL
-- 'auto'       — auto-generated by product_type trigger
-- 'sushi_auto' — auto-generated by sushi_grade trigger
ALTER TABLE catalog_product_seasonality
ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual';

-- ── 2. Composite lookup index ────────────────────────────────────────────────
-- Covers the main query pattern: WHERE product_id = $1 AND region_code = $2 AND month = $3
-- Dedicated covering index with status for index-only scans on best-in-season
CREATE INDEX IF NOT EXISTS idx_seasonality_lookup
    ON catalog_product_seasonality (product_id, region_code, month, status);

-- ── 3. Auto-update updated_at on any change ─────────────────────────────────
CREATE OR REPLACE FUNCTION fn_seasonality_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_seasonality_updated_at ON catalog_product_seasonality;
CREATE TRIGGER trg_seasonality_updated_at
    BEFORE UPDATE ON catalog_product_seasonality
    FOR EACH ROW
    EXECUTE FUNCTION fn_seasonality_updated_at();

-- ── 4. Sushi-grade → true: generate seasonality with peak support ────────────
--
-- Peak months logic for sushi fish:
--   - Summer months (Jun–Aug) are peak for most fish (best catches)
--   - Shoulder months (availability_months = true but not peak) → good
--   - Off months (availability_months = false) → off
--
-- Uses BEFORE UPDATE to also set availability_model

CREATE OR REPLACE FUNCTION fn_auto_seasonality_on_sushi_grade()
RETURNS TRIGGER AS $$
DECLARE
    peak_months INT[] := ARRAY[6, 7, 8]; -- Jun, Jul, Aug (summer peak for most fish)
BEGIN
    -- ── sushi_grade changed to TRUE ──
    IF NEW.sushi_grade IS DISTINCT FROM OLD.sushi_grade
       AND NEW.sushi_grade = true
       AND NEW.product_type IN ('fish', 'seafood')
    THEN
        -- Insert seasonality rows for all 4 regions × 12 months
        -- With peak/good/off status (not just good/off)
        INSERT INTO catalog_product_seasonality
            (product_id, region_code, month, status, source, updated_at)
        SELECT
            NEW.id,
            region,
            gs.month,
            CASE
                -- availability_months exists and month is available
                WHEN NEW.availability_months IS NOT NULL
                     AND array_length(NEW.availability_months, 1) >= gs.month
                     AND NEW.availability_months[gs.month] = true
                THEN
                    CASE WHEN gs.month = ANY(peak_months) THEN 'peak' ELSE 'good' END
                -- availability_months is NULL → assume all year
                WHEN NEW.availability_months IS NULL
                THEN
                    CASE WHEN gs.month = ANY(peak_months) THEN 'peak' ELSE 'good' END
                -- month not available
                ELSE 'off'
            END AS status,
            'sushi_auto' AS source,
            now() AS updated_at
        FROM generate_series(1, 12) AS gs(month)
        CROSS JOIN (VALUES ('GLOBAL'), ('PL'), ('EU'), ('UA')) AS regions(region)
        ON CONFLICT (product_id, region_code, month)
        DO UPDATE SET
            -- Only upgrade status, never downgrade manual entries
            status = CASE
                WHEN catalog_product_seasonality.source = 'manual' THEN catalog_product_seasonality.status
                ELSE EXCLUDED.status
            END,
            source = CASE
                WHEN catalog_product_seasonality.source = 'manual' THEN 'manual'
                ELSE 'sushi_auto'
            END,
            updated_at = now();

        -- Ensure availability_model is seasonal_calendar
        IF NEW.availability_model IS NULL OR NEW.availability_model = 'all_year' THEN
            NEW.availability_model := 'seasonal_calendar';
        END IF;

        RAISE NOTICE '🍣 Auto-generated seasonality for sushi-grade product % (%)',
            COALESCE(NEW.slug, 'unknown'), NEW.id;
    END IF;

    -- ── sushi_grade changed to FALSE ──
    -- Clean up only rows WE created (source = 'sushi_auto')
    -- Never delete manual entries
    IF NEW.sushi_grade IS DISTINCT FROM OLD.sushi_grade
       AND (NEW.sushi_grade = false OR NEW.sushi_grade IS NULL)
       AND OLD.sushi_grade = true
    THEN
        DELETE FROM catalog_product_seasonality
        WHERE product_id = NEW.id
          AND source = 'sushi_auto';

        RAISE NOTICE '🧹 Cleaned up sushi_auto seasonality for product % (%)',
            COALESCE(NEW.slug, 'unknown'), NEW.id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_auto_seasonality_sushi_grade ON catalog_ingredients;
CREATE TRIGGER trg_auto_seasonality_sushi_grade
    BEFORE UPDATE OF sushi_grade ON catalog_ingredients
    FOR EACH ROW
    EXECUTE FUNCTION fn_auto_seasonality_on_sushi_grade();

-- ── 5. Backfill source for existing rows ─────────────────────────────────────
-- Mark all existing rows as 'auto' (they came from earlier triggers/migrations)
UPDATE catalog_product_seasonality
SET source = 'auto'
WHERE source = 'manual';

-- ── 6. Backfill updated_at for existing rows ────────────────────────────────
UPDATE catalog_product_seasonality
SET updated_at = created_at
WHERE updated_at IS NULL;

-- ── 7. Backfill seasonality for sushi_grade=true fish that lack rows ────────
INSERT INTO catalog_product_seasonality
    (product_id, region_code, month, status, source, updated_at)
SELECT
    ci.id AS product_id,
    region,
    gs.month,
    CASE
        WHEN ci.availability_months IS NOT NULL
             AND array_length(ci.availability_months, 1) >= gs.month
             AND ci.availability_months[gs.month] = true
        THEN CASE WHEN gs.month IN (6, 7, 8) THEN 'peak' ELSE 'good' END
        WHEN ci.availability_months IS NULL
        THEN CASE WHEN gs.month IN (6, 7, 8) THEN 'peak' ELSE 'good' END
        ELSE 'off'
    END AS status,
    'sushi_auto' AS source,
    now() AS updated_at
FROM catalog_ingredients ci
CROSS JOIN generate_series(1, 12) AS gs(month)
CROSS JOIN (VALUES ('GLOBAL'), ('PL'), ('EU'), ('UA')) AS regions(region)
WHERE ci.product_type IN ('fish', 'seafood')
  AND ci.sushi_grade = true
  AND ci.is_active = true
ON CONFLICT (product_id, region_code, month) DO NOTHING;

-- Ensure availability_model for sushi fish
UPDATE catalog_ingredients
SET availability_model = 'seasonal_calendar'
WHERE product_type IN ('fish', 'seafood')
  AND sushi_grade = true
  AND (availability_model IS NULL OR availability_model = 'all_year');

-- ── 8. Set eel as sushi_grade = true (unagi = classic sushi ingredient) ─────
UPDATE catalog_ingredients
SET sushi_grade = true
WHERE slug = 'eel'
  AND (sushi_grade IS NULL OR sushi_grade = false);
